# Amaral Turnip 4.2 — A740 Aurora experimental profile
# Target: Qualcomm Adreno 740 / Snapdragon 8 Gen 2
# Experimental: validate through Amaral Driver Lab before universal adoption.

[ir3]
gcm=1

[shader_cache]
size_gb=4

[suballocator]
pipeline_block_kb=512
kgsl_profiling_block_kb=512

[compatibility.zelda]
tu_dont_care_as_load=true
tu_allow_oob_indirect_ubo_loads=true
